blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Default:index }
blog_hello: 
    path: /hello-world
    defaults: { _controller: BlogBundle:Blog:index }
blog_voir: 
    path: /blog/post/{id}
    defaults: { _controller: BlogBundle:Blog:voir }
    
blog_voirb: 
    path: /blog/postb/{id}
    defaults: { _controller: BlogBundle:Blog:voirb }

blog_voirc: 
    path: /blog/postc/{id}
    defaults: { _controller: BlogBundle:Blog:voirc }
    
blog_ajouter: 
    path: /blog/ajouter 
    defaults: { _controller: BlogBundle:Blog:ajouter }
    
    
    